### ISSUE TITLE
Update for PocketMine 1.6

### ISSUE THREAD

**Issue by nooneusethisname** [Falkirks/Specter#26]
![image](https://cloud.githubusercontent.com/assets/16216792/12214824/e7b8a988-b6d5-11e5-9375-09426ac76dbd.png)

**Comment by nooneusethisname** [comment]
Please help

**Comment by XiangZhao969** [comment]
I'm using ImagicalMine and i met this too

**Comment by PEMapModder** [comment]
I don't think we support ImagicalMine.

**Comment by PEMapModder** [comment]
This issue is caused by the removal of Server::getUpdater() on ImagicalMine and/or Katana/Steadfast2.

As these unofficial modifications of PocketMine are not supported, this issue is to be closed.

@Falkirks please reopen this issue if you want to provide support for unofficial changes of PocketMine.
